### ISSUE TITLE
System.IO.FileLoadException with "PubNub-Messaging"

### ISSUE THREAD

**Issue by chaoseternai** [ringcentral/ringcentral-csharp-client#13] opened 2017-07-05 23:24 UTC
Hello,

I'm trying to make a basic program that reads inbound numbers. At the moment I just have the basic initialization, authorization, and subscription included within my code from the README, but I'm getting this error: 

"System.IO.FileLoadException: Could not load file or assembly 'PubNub-Messaging, Version=1.0.6201.20023, Culture=neutral, PublicKeyToken=dc66f52ce6619f44' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at RingCentral.SubscriptionService.Alive()
   at RingCentral.SubscriptionService.<Register>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at InboundNumber.Program.<>c.<<Main>b__0_0>d.MoveNext() in C:\Users\james.ho\Documents\Visual Studio 2015\Projects\RingCentral\InboundNumber\InboundNumber\Program.cs:line 63
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at InboundNumber.Program.Main(String[] argsIgnore) in C:\Users\james.ho\Documents\Visual Studio 2015\Projects\RingCentral\InboundNumber\InboundNumber\Program.cs:line 14"

I have tried re-installing the Nuget packages and that fixed some previous issues, but I'm not too sure how to resolve this one with PubNub. I have tried using the latest version and the one installed with installing the package for RingCentral but neither seems to work.

**Comment by tylerlong** [comment] 2017-07-07 11:10
I cannot reproduce the issue. Could you please tell me how to reproduce it?

I just created a new project and `Install-Package RingCentral.Client` and I could add the library successfully without any issues. I could also compile the project.

**Comment by tylerlong** [comment] 2017-08-04 09:37
Closing. Feel free to reopen if you still have the issue.

**Closed by tylerlong** 2017-08-04 09:37 UTC
